@startuml GridWarFogComponent

class GridMapWarFogComponent{
    +GridMapWarFogComponent(const FObjectInitializer& ObjectInitializer): void
    +OnRegister() : void
    +OnUnregister() : void

    -
}

@enduml